### Create User

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"test2@test.com",
    "password":"Test@1234"
}

### Get User by Id

GET http://localhost:3000/auth/find/2
Content-Type: application/json

### Get all users

GET http://localhost:3000/auth/find
Content-Type: application/json

### Update User
POST http://localhost:3000/auth/update
Content-Type: application/json

{
    "id":1,
    "email":"sri@test.com"
}

### Remove User
POST http://localhost:3000/auth/delete/2
Content-Type: application/json

